server.port=8080
server.servlet.context-path=/philokalo

spring.application.name=philokalo-server
spring.datasource.url=jdbc:mysql://localhost:3306/philokalodb
spring.datasource.username=root
spring.datasource.password=Admin@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

logging.level.org.springframework.security=DEBUG

spring.jackson.time-zone=Asia/Ho_Chi_Minh

app.jwt.signer-key=A0lMZqvAdnvCuyfbGxxttCmoSbzX4zkG7Si0UhkhrpSLa4TZCaHoe2OlUdEEdU-Utw-JLMthboIXg4fWzXvkfEgfrg97Qn6A2xEyapcrHvC4FB0utbD-6rVdL4XHGKVyDULNaPtB0wOSxCNn5BpGs5pEbVor6gAf6SVh9NLgqnFr2PGGv-FrrT8gZxO91r5Bzw4YMQtf3N-Vkv-80LZfd4XO0yi3vXd1OgFAM4FJs4L9IJ9fQD0_jNMV6uwD51Ch
app.jwt.algorithm=HS512
app.jwt.valid-duration=259200
app.jwt.refreshable-duration=345600

app.cloudinary.cloud-name=philokalo-cloud
app.cloudinary.api-key=341421257722269
app.cloudinary.api-secret=jRKv8uK_Av6jCJcV80qQNyrTsHk
app.cloudinary.folder.avatar=philokalo-cloud/avatar
app.cloudinary.folder.gallery=philokalo-cloud/gallery
app.cloudinary.size=10485760